project:
  name: infrastructure-test
  regions:
    - ap-southeast-2
  parameters:
    AllowedIP: 0.0.0.0/32
    KeyName: dummy-key
    S3BucketName: ${ARTIFACT_BUCKET}
  package_lambda: false

tests:
  infrastructure-test:
    template: Task2/root-stack.yaml
    regions:
      - ap-southeast-2
    parameters:
      AllowedIP: 0.0.0.0/32
      KeyName: dummy-key
      S3BucketName: ${ARTIFACT_BUCKET} 