version: 0.2

phases:
  install:
    commands:
      - sudo yum update -y
      - sudo yum install -y python3 python3-pip
      - python3 -m pip install --user cfn-lint taskcat
      - export PATH=$PATH:$HOME/.local/bin
  
  build:
    commands:
      - echo "Running cfn-lint validation..."
      - cfn-lint --config-file Task2/cfnlintrc.yml Task2/root-stack.yaml Task2/modules/*.yaml
      
      - echo "Packaging templates..."
      - aws cloudformation package --template-file Task2/root-stack.yaml --s3-bucket "${ARTIFACT_BUCKET}" --output-template-file Task2/packaged-root-stack.yaml
      
      - echo "Running taskcat test..."
      - taskcat test run -d

artifacts:
  files:
    - Task2/packaged-root-stack.yaml
    - Task2/modules/*
    - .taskcat.yml
  base-directory: .