version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install cfn-lint taskcat
  
  pre_build:
    commands:
      - echo "Preparing for template validation..."
  
  build:
    commands:
      - echo "Running CloudFormation template validation..."
      - echo "Step 1: Running cfn-lint validation..."
      - |
        cfn-lint --config-file Task2/.cfnlintrc.yml Task2/root-stack.yaml Task2/modules/*.yaml || \
        if [ $? -eq 4 ]; then echo "Warnings found but continuing..."; else exit $?; fi
      - echo "Step 2: Running taskcat tests..."
      - cd Task2 && taskcat test run && cd ..
      - |
        aws cloudformation package \
        --template-file Task2/root-stack.yaml \
        --s3-bucket ${ARTIFACT_BUCKET} \
        --output-template-file Task2/packaged-root-stack.yaml
      - echo "Step 3: Packaging templates..."
  
  post_build:
    commands:
      - echo "Template validation, testing, and packaging complete"

artifacts:
  files:
    - Task2/packaged-root-stack.yaml
    - Task2/modules/*
    - Task2/taskcat.yml
  base-directory: . 