version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: !Ref AWS::Region
    PYTHONUNBUFFERED: 1
  parameter-store:
    # Add any SSM parameters if needed
    # ARTIFACT_BUCKET: /my/parameter/path

phases:
  install:
    commands:
      - sudo yum update -y
      - sudo yum install -y python3 python3-pip
      - python3 -m pip install --upgrade pip
      - python3 -m pip install cfn-lint taskcat
  
  pre_build:
    commands:
      - echo "Checking for changes in Task2..."
      
  build:
    commands:
      - echo "Running CloudFormation template validation..."
      - echo "Step 1. Running cfn-lint validation..."
      - "cfn-lint --config-file Task2/.cfnlintrc.yml Task2/root-stack.yaml Task2/modules/*.yaml || ([ $? -eq 4 ] && echo 'Warnings found but continuing...' || exit $?)"
      - echo "Step 2. Running taskcat tests..."
      - "cd Task2 && taskcat test run && cd .."
      - echo "Step 3. Packaging templates..."
      - "aws cloudformation package --template-file Task2/root-stack.yaml --s3-bucket ${ARTIFACT_BUCKET} --output-template-file Task2/packaged-root-stack.yaml"
  
  post_build:
    commands:
      - echo "Template validation, testing, and packaging complete"

artifacts:
  files:
    - Task2/packaged-root-stack.yaml
    - Task2/modules/*
    - Task2/.taskcat.yml
  base-directory: . 